- hosts: all
  any_errors_fatal: True
  vars_files:
    - "{{ playbook_dir }}/vars.yaml"
  tasks:
    - name: Install release RPM
      yum:
        name: "{{ release_rpm }}"

- hosts: localhost
  connection: local
  tasks:
    - name: playbook_dir test
      debug:
        msg: "{{ log_path }}"
      tags: test

- hosts: "vm-type=ovirt-engine"
  any_errors_fatal: True
  roles:
    - storage_and_ldap
  tasks:
    - name: Install Engine
      script: "{{ playbook_dir }}/setup_engine.sh"
      tags: install_storage

- hosts: localhost
  connection: local
  any_errors_fatal: True
  vars_files:
    - "{{ playbook_dir }}/vars.yaml"
  environment:
    SUITE: "{{ suite_name }}"
    ENGINE_ANSWER_FILE: "{{ playbook_dir }}/engine-answer-file.conf"
    PYTHONPATH: "{{ lookup('env', 'PYTHONPATH') }}:{{ playbook_dir }}"
  tags: sdk_scripts
  tasks:
    - name: Build sdk_scripts list
      find:
        path: "{{ playbook_dir }}/sdk_scripts"
        patterns: "*.py"
      register: sdk_scripts_list
      tags: deploy
    - name: Deploy env
      block:
        - name: Run sdk scripts
          command: lago ovirt runtest "{{ item.path }}"
          with_items: "{{ sdk_scripts_list.files | sort(attribute='path') }}"
      always:
        - include: collect_logs_task.yaml
          vars:
            dest: "{{ log_path }}/deploy"

      tags: deploy
    - name: Stop env
      command: lago ovirt stop
